quotes = [
    ('', ''),
    ('"', '"'),
    ('`', '`'),
    ('[', ']'),
    # TODO: We aren't testing single-quotes because currently `FROM 'tbl'` fails to parse:
    # ProjectionsOfQuotedIdentifiers.s line 13:56 - <table or subquery real> expected, got ''tbl''
    #    13: WITH tbl(name) AS (SELECT 'Peter') SELECT tbl.name FROM 'tbl';

    # ("'", "'"),
]


def main():
    with open('ProjectionsOfQuotedIdentifiers.s', 'wt') as f:
        print('--\n-- DO NOT MODIFY BY HAND, THIS FILE IS GENERATED BY generate_test.py\n--\n', file=f)
        for (q1_start, q1_end) in quotes:
            for (q2_start, q2_end) in quotes:
                print(f"WITH {q1_start}tbl{q1_end}(name) AS (SELECT 'Peter') SELECT tbl.name FROM {q2_start}tbl{q2_end};", file=f)
                print(f"WITH tbl({q1_start}name{q1_end}) AS (SELECT 'Peter') SELECT tbl.{q2_start}name{q2_end} FROM tbl;\n", file=f)


if __name__ == '__main__':
    main()
