--
-- DO NOT MODIFY BY HAND, THIS FILE IS GENERATED BY generate_test.py
--

WITH tbl(name) AS (SELECT 'Peter') SELECT tbl.name FROM tbl;
WITH tbl(name) AS (SELECT 'Peter') SELECT tbl.name FROM tbl;

WITH tbl(name) AS (SELECT 'Peter') SELECT tbl.name FROM "tbl";
WITH tbl(name) AS (SELECT 'Peter') SELECT tbl."name" FROM tbl;

WITH tbl(name) AS (SELECT 'Peter') SELECT tbl.name FROM `tbl`;
WITH tbl(name) AS (SELECT 'Peter') SELECT tbl.`name` FROM tbl;

WITH tbl(name) AS (SELECT 'Peter') SELECT tbl.name FROM [tbl];
WITH tbl(name) AS (SELECT 'Peter') SELECT tbl.[name] FROM tbl;

WITH "tbl"(name) AS (SELECT 'Peter') SELECT tbl.name FROM tbl;
WITH tbl("name") AS (SELECT 'Peter') SELECT tbl.name FROM tbl;

WITH "tbl"(name) AS (SELECT 'Peter') SELECT tbl.name FROM "tbl";
WITH tbl("name") AS (SELECT 'Peter') SELECT tbl."name" FROM tbl;

WITH "tbl"(name) AS (SELECT 'Peter') SELECT tbl.name FROM `tbl`;
WITH tbl("name") AS (SELECT 'Peter') SELECT tbl.`name` FROM tbl;

WITH "tbl"(name) AS (SELECT 'Peter') SELECT tbl.name FROM [tbl];
WITH tbl("name") AS (SELECT 'Peter') SELECT tbl.[name] FROM tbl;

WITH `tbl`(name) AS (SELECT 'Peter') SELECT tbl.name FROM tbl;
WITH tbl(`name`) AS (SELECT 'Peter') SELECT tbl.name FROM tbl;

WITH `tbl`(name) AS (SELECT 'Peter') SELECT tbl.name FROM "tbl";
WITH tbl(`name`) AS (SELECT 'Peter') SELECT tbl."name" FROM tbl;

WITH `tbl`(name) AS (SELECT 'Peter') SELECT tbl.name FROM `tbl`;
WITH tbl(`name`) AS (SELECT 'Peter') SELECT tbl.`name` FROM tbl;

WITH `tbl`(name) AS (SELECT 'Peter') SELECT tbl.name FROM [tbl];
WITH tbl(`name`) AS (SELECT 'Peter') SELECT tbl.[name] FROM tbl;

WITH [tbl](name) AS (SELECT 'Peter') SELECT tbl.name FROM tbl;
WITH tbl([name]) AS (SELECT 'Peter') SELECT tbl.name FROM tbl;

WITH [tbl](name) AS (SELECT 'Peter') SELECT tbl.name FROM "tbl";
WITH tbl([name]) AS (SELECT 'Peter') SELECT tbl."name" FROM tbl;

WITH [tbl](name) AS (SELECT 'Peter') SELECT tbl.name FROM `tbl`;
WITH tbl([name]) AS (SELECT 'Peter') SELECT tbl.`name` FROM tbl;

WITH [tbl](name) AS (SELECT 'Peter') SELECT tbl.name FROM [tbl];
WITH tbl([name]) AS (SELECT 'Peter') SELECT tbl.[name] FROM tbl;

