package com.alecstrong.sql.psi.core.psi

import com.intellij.psi.PsiElement

interface TableElement : SqlCompositeElement, Queryable, SchemaContributor {
  /**
   * Used for IDE if this table should pop up in auto-completion.
   */
  val synthesized: Boolean

  /**
   * Used for SQLDelight if this table should be generated by default.
   */
  val virtual: Boolean
}

interface Queryable : PsiElement {
  fun tableExposed(): LazyQuery
}
