name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version-file: .github/workflows/.java-version

    - uses: gradle/actions/setup-gradle@v4

    - name: Execute a build
      run: ./gradlew build :sample-plugin:buildPlugin --stacktrace

    - run: ./gradlew runPluginVerifier

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
